general {
    before_sleep_cmd = ~/.config/hypr/lock.sh
}

listener {
    timeout = 300
    on-timeout = ~/.config/hypr/lock.sh
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r
}
