[modules]
left =   [ ["Workspaces", "Tray"] ]
center = [ ["WindowTitle"] ]
right =  [ ["MediaPlayer", "SystemInfo"], ["Clock", "Privacy", "Settings"] ]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = true
max_workspaces = 12

[appearance]
scale_factor=1.25
opacity=0

success_color = "#a6e3a1"
text_color = "#333333"

workspace_colors = [ "#07378B", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#aaaaaa"
weak = "#eeeeee"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
