#General
set -g base-index 1
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=default'
set -g status-left-style 'fg=#1F1F28,bg=#956FB8,bold'
set -g status-left ' #S'
set -g status-left-length 20
set -g status-right ''
set -g detach-on-destroy off
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

set -g window-status-format '#{?window_active,#[bg=colour31,fg=black],#{?window_last_flag,#[bg=colour240],#{?window_activity_flag,#[bg=colour236],#[default]}}} #I:#W #[default]'

set -g automatic-rename on
set -g automatic-rename-format '#(~/.config/tmux/rename_format.sh "#{pane_current_path}") | #{b:pane_current_command}'

# Set colorschemes properly
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"

# Set tmux prefix to space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Emulate vim keybinds
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

bind w choose-tree -w

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection
set -g allow-passthrough on
set -s set-clipboard on
set -g mode-style 'fg=#1F1F29,bg=#7E9CD8'

bind y copy-mode

